### ISSUE TITLE
Use JSON file to store students data

### ISSUE THREAD

**Issue by jsstrn** [jsstrn/ga-wdi-class#11]
We should move our data into a JSON file, then read the JSON file and iterate through the values. I'll try and work on this.

**Comment by caalberts** [comment]
:+1:

**Comment by caalberts** [comment]
How's it going?

**Comment by jsstrn** [comment]
I've created a separate branch for this feature (unimaginatively) called "feature-branch". There's a js/data.json file as well as a v2.html page for testing.

**Comment by jsstrn** [comment]
I managed to display names and images from the JSON file. It is live here: https://jsstrn.github.io/ga-wdi-class/v2
