### ISSUE TITLE
Update gh-pages branch

### ISSUE THREAD

**Issue by caalberts** [jsstrn/ga-wdi-class#12]
@jsstrn  need help on this.

**Comment by jsstrn** [comment]
@caalberts Done. Layout has gone haywire though.

**Comment by caalberts** [comment]
:+1: @jsstrn I think because of the irregular photo dimensions. Hence need to crop to square.
The social buttons might cause some layout issues too.

**Comment by jsstrn** [comment]
@caalberts True, cropping of images is important or we can fix the dimensions of the panels (this way may be easier).

Also, Tian's photo is not displaying for some reason.
