### ISSUE TITLE
Crop and center faces in photos

### ISSUE THREAD

**Issue by caalberts** [jsstrn/ga-wdi-class#16]
Now that cropping to square is done, let's see if we can center on the **faces**

**Comment by jsstrn** [comment]
We will need to use a face recognition API to first detect the face. You can see an example of this [here](https://lambdal.com/face-recognition-api#src). Using [Steve's photo](https://jsstrn.github.io/ga-wdi-class/img/Steve.jpg) as an example, we get back this JSON file: 

``` json
{
    "status": "success",
    "images": [
        "https://jsstrn.github.io/ga-wdi-class/img/Steve.jpg"
    ],
    "photos": [
        {
            "url": "https://jsstrn.github.io/ga-wdi-class/img/Steve.jpg",
            "width": 500,
            "tags": [
                {
                    "eye_left": {
                        "y": 229,
                        "x": 321
                    },
                    "confidence": 0.978945010372561,
                    "center": {
                        "y": 249,
                        "x": 292
                    },
                    "width": 183,
                    "mouth_left": {
                        "y": 310,
                        "x": 258
                    },
                    "height": 183,
                    "mouth_right": {
                        "y": 310,
                        "x": 324
                    },
                    "mouth_center": {
                        "y": 310,
                        "x": 291
                    },
                    "nose": {
                        "y": 266,
                        "x": 288
                    },
                    "tid": "31337",
                    "attributes": [
                        {
                            "smile_rating": 0.08,
                            "smiling": false,
                            "confidence": 0.08
                        }
                    ],
                    "eye_right": {
                        "y": 227,
                        "x": 258
                    }
                }
            ],
            "height": 889
        }
    ]
}
```

![screen shot 2015-11-07 at 8 56 19 am](https://cloud.githubusercontent.com/assets/1199611/11012353/8ab59464-852d-11e5-8f58-578b397b39d7.png)

**Comment by jsstrn** [comment]
We might be able to then use `object-position` as mentioned by @cbas in class yesterday (see [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position))

``` css
img {
  object-position: 292px 249px
}
```

**Comment by caalberts** [comment]
cool stuff

**Comment by caalberts** [comment]
Hmm okay I'm thinking of a script to querySelectorAll('.profile-photo'), then forEach(photo) get the image URL and call the API to search the face, then apply object-position accordingly. I'll give it a try tomorrow. @jsstrn

**Comment by caalberts** [comment]
Will try this https://market.mashape.com/apicloud/facerect since it's free

**Comment by jsstrn** [comment]
@caalberts I like that approach! :+1: :+1:

**Comment by caalberts** [comment]
@cbas I'm trying to use a mashape API for the face recognition. How would you recommend handling API keys in javascript without exposing the key? I suppose for 'real' applications we wouldn't want the key to be visible by anyone visiting the site.

**Comment by sebdeckers** [comment]
@caalberts Can't really hide the API key on the client side. Only in server side code can you hide it from prying eyes, typically by setting it as an environment variable on the server and NEVER committing it into the Git repository (if you ever do, consider the key compromised and generate another).

Solutions are to either have API access restricted to your website domain (and `localhost` for testing) to prevent casual abuse. Alternatively proxy the API calls through your server where keys can be protected using above method.

**Comment by caalberts** [comment]
@jsstrn face recognition and centering is done, but still need to rescale the images. I haven't pushed to Github for the reason above.

**Comment by sebdeckers** [comment]
BTW Doing the API calls for face detection on every visit to the page introduces a lot of repeated work and latency. Might make sense to do this at build time – i.e. when you deploy the code for a new release.

Consider using a service like Travis to run your build scripts (and tests, once we have them), then deploy to [Surge.sh](https://surge.sh) for hosting.

**Comment by sebdeckers** [comment]
That would allow Travis env vars to contain the API keys in encrypted form.

http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by caalberts** [comment]
@cbas Agree on the latency and unnecessary repeated calls. When @jsstrn is done with the JSON file we can store the facial data in it.

**Comment by caalberts** [comment]
https://github.com/caalberts/ga-wdi-class/tree/face-recognition
- facerect API to find the location of faces to be stored for later use
- object-position to put the faces as close to the center as possible. Some are not possible as they're too close to the edges (e.g Irvin).
  @jsstrn @cbas

**Comment by caalberts** [comment]
@cbas should the build script you mentioned above be in package.json or in travis.yml?
