### ISSUE TITLE
Travis to run script and deploy to Surge.sh

### ISSUE THREAD

**Issue by caalberts** [jsstrn/ga-wdi-class#32]
Based on suggestion from issue https://github.com/jsstrn/ga-wdi-class/issues/16

**Comment by caalberts** [comment]
Deployed to surge.sh http://ga-wdi-class.surge.sh/
@cbas @jsstrn

**Comment by sebdeckers** [comment]
:+1: Sweet!

**Comment by sebdeckers** [comment]
Where is the code?

**Comment by caalberts** [comment]
https://github.com/caalberts/ga-wdi-class/tree/travis

Right now it's just taking any commit to my repo and publish it to surge. I've not figured out how to make Travis run the script for the API

**Comment by caalberts** [comment]
Latest commit https://github.com/caalberts/ga-wdi-class/tree/travis with script to read the faces from data.json
@cbas when travis run the node script, I got the following. Seems like node doesn't have fetch yet?

```
$ node ./js/face_detect.js
/home/travis/build/caalberts/ga-wdi-class/js/face_detect.js:7
fetch('js/data.json')
^
ReferenceError: fetch is not defined
    at Object.<anonymous> (/home/travis/build/caalberts/ga-wdi-class/js/face_detect.js:7:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
The command "node ./js/face_detect.js" exited with 1.
Done. Your build exited with 1.
```

**Comment by caalberts** [comment]
http://ga-wdi-class.surge.sh/v2
http://ga-wdi-class.surge.sh/js/dataWithFace.json
