### ISSUE TITLE
Auto crop images to square format

### ISSUE THREAD

**Issue by caalberts** [jsstrn/ga-wdi-class#8]
New feature request
- automatically crop images to square format

**Comment by jsstrn** [comment]
This is a good feature request. :+1:

**Comment by caalberts** [comment]
@cbas do you know how we can crop **both** landscape and portrait images into square? I found ways to do _either_, but not **both**.

**Comment by sebdeckers** [comment]
Something like this?

``` css
background-image: url(img/man.png);
background-position: center;
background-size: cover;
```

**Comment by caalberts** [comment]
I considered using the image as the background url, but that means we need to apply custom css selector to every person.

Anyway, this is what I did, which only cropped landscape to square, not portrait to square.

```
<div class="crop">
  <!-- Add your image path in the src attribute -->
  <img src="img/tian.jpg" alt="man" class="profile-photo img-rounded">
</div>
```

```
.crop {
  position: relative;
  width: 256px;
  height: 256px;
  margin: auto;
  overflow: hidden;
  border-radius: 5px;
}
.profile-photo {
  position: absolute;
  left: 50%;
  top: 50%;
  height: 100%;
  width: auto;
  transform: translate(-50%,-50%);
}
```

**Comment by sebdeckers** [comment]
Ooooh let's try this!

https://medium.com/@chrisnager/center-and-crop-images-with-a-single-line-of-css-ad140d5b4a87

``` css
img {
  object-fit: cover;
}
```

No need for `background` hacks...

**Comment by caalberts** [comment]
Ok will try

**Comment by caalberts** [comment]
It works!!! :open_mouth:

**Comment by jsstrn** [comment]
:+1:  :+1:

**Comment by sebdeckers** [comment]
:+1: Show it tomorrow morning!
